### ISSUE TITLE
Support CasperJS capture method

### ISSUE THREAD

**Issue by noodny** [WaterfallEngineering/SpookyJS#127]
As described in http://docs.casperjs.org/en/latest/modules/casper.html#capture
Would it be possible to support this feature with your current approach?

**Comment by lawnsea** [comment]
Looking at the docs, `capture` is a helper method called in a step. You can do this now:

```javascript
spooky.start('http://www.google.fr/', function() {
    this.capture('google.png', {
        top: 100,
        left: 100,
        width: 500,
        height: 400
    });
});

spooky.run();
```
