### ISSUE TITLE
Can SpookyJS work in Node.js on microsoft windows? 

### ISSUE THREAD

**Issue by selukov** [WaterfallEngineering/SpookyJS#131]
This example displays the correct log on ubuntu, but what happens under microsoft windows is not clear. 
https://github.com/selukov/Frontend_tests/blob/master/app1.js
Is there any opportunity to reveal that happens to spooky?

P.S. CasperJs and PhantomJs work on windows normally, I established exe files according to the instruction, if to put through npm don't work http://docs.casperjs.org/en/latest/modules/casper.html#fill

**Comment by laggingreflex** [comment]
Came here to inquire just this.

I noticed that Spooky passes `'casperjs'` as command argument to `spawn`, which throws an ENOENT error. I replaced it with `'casper.bat'` 

    var defaults = {
        ...
        child: {
            command: 'casperjs' + (process.platform === 'win32' ? '.exe' : ''),
            ...
        },
        ...
    };

https://github.com/WaterfallEngineering/SpookyJS/blob/master/lib/spooky.js#L26

which stopped the error at least, but it still doesn't work past that point, it seems stuck somewhere. 

I also noticed certain path joins `__dirname + ..` that better ought to be `path.join(...)` for cross-platform use. 

There are most definitely other issues too.

**Comment by lawnsea** [comment]
@selukov try overriding the `child.command` option with the correct command is to start CasperJS in Windows.

> it still doesn't work past that point, it seems stuck somewhere.

@laggingreflex I'm afraid that I need more information than that. Please open a new issue with an example script or otherwise explicit instructions for reproducing the failure you're seeing.
