### ISSUE TITLE
Can´t load casper module placed at the same parent node_modules directory

### ISSUE THREAD

**Issue by jcalvarad** [WaterfallEngineering/SpookyJS#132]
I only have spookyjs installed in the node_modules folder of my project, but I am only able to successfully execute my scripts (or the example one included) when casperjs is installed with the global (-g) flag, not when I have it in the same nodes_modules as spookyjs.

Is there any configuration or step that I may be overlooking here?
Thank you!

**Comment by lawnsea** [comment]
If `casperjs` is not in the path, you'll need to pass the full path to the binary in the [`child.command` config option](https://github.com/WaterfallEngineering/SpookyJS/blob/master/lib/spooky.js#L26).

**Comment by jcalvarad** [comment]
Thanks for the quick help!
