### ISSUE TITLE
PhantomJS not start with cyrillic string inside

### ISSUE THREAD

**Issue by CubixSystem** [WaterfallEngineering/SpookyJS#137]
PhantomJS not start with cyrillic string inside casper context.
```javascript
spooky.then(function () {
    var thisNotWork = "Фантом зависнет";
});
```
Maybe it's casper issue?

**Comment by lawnsea** [comment]
This is probably a duplicate of #110. It's fixed in https://github.com/WaterfallEngineering/SpookyJS/commit/32353886f609b5671960cfaed50f2f9b8189d2de.

**Comment by CubixSystem** [comment]
Wow, big thanks for fast response!
It works, I have spooky v. 2.6.1 without this fix.
