### ISSUE TITLE
SyntaxError: Unexpected token E at StreamClient._onData (tiny-jsonrpc/lib/tiny-jsonrpc/stream-client.js:86:25)

### ISSUE THREAD

**Issue by pauljohncleary** [WaterfallEngineering/SpookyJS#98]
Running into this error when crawling some sites.

```````
SyntaxError: Unexpected token E
    at Object.parse (native)
    at StreamClient._onData (/home/paul/plucky-crawler-server/node_modules/spooky/node_modules/tiny-jsonrpc/lib/tiny-jsonrpc/stream-client.js:86:25)
    at RequestStream.EventEmitter.emit (events.js:117:20)
    at RequestStream.<anonymous> (/home/paul/plucky-crawler-server/node_modules/spooky/lib/spooky/request-stream.js:47:14)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```````
I've added a console.log to look at the response in:
```````
StreamClient.prototype._onData()
```````
The error looks like it's triggered when a response like the following is received:
```````
Error 403: Directory Listing Denied
Directory listing denied
```````

Where should I catch errors like this? I'm writing a crawler that needs to be able to handle these errors.

I'm happy to do the pull request if you can point me in the right direction. 

Thanks.

**Comment by dbuezas** [comment]
There is another situation in which this error still occurs: when one needs to add more steps after calling ```spooky.run()```.

What happens there ist that the ```spooky.run``` function automatically closes casperjs when it finishes doing all steps. If any steps are added after casper finished the initial batch, the http transport fails and you get the 403.

The only solution I found is to call ```spooky.run``` with an empty callback and then exit casperjs manually.

```
var noop = function(){
   // this empty callback will avoid casper getting closed
}
spooky.then(function(){  ...  });
spooky.run(noop);
setTimeout(function(){
   spooky.then(function(){  ...  });
   spooky.run(noop);
}, 1000);
```

It is hacky but it works. The order of the steps gets scrambled but you can handle that by manually getting sure you add steps as the previous ones get completed.
